[mypy]
ignore_errors = True
check_untyped_defs = False
disallow_untyped_defs = False
disallow_incomplete_defs = False
warn_return_any = False
warn_unused_ignores = False
strict = False

# Ignore specific modules
[mypy-twstock.*]
ignore_errors = True
